name: Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install FTP Client
        run: sudo apt-get install -y lftp

      - name: Deploy via FTP
        run: |
          lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD -p $FTP_PORT $FTP_HOSTNAME; set ssl:verify-certificate no; mirror -Rnev ./ /htdocs/laravel"
        env:
          FTP_HOSTNAME: ${{ secrets.FTP_HOSTNAME }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_PORT: ${{ secrets.FTP_PORT }}
